import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, Camera, Quote, Users } from 'lucide-react';
import { SectionHeading } from '../components/SectionHeading';
import { SponsorRibbon } from '../components/SponsorRibbon';
import { CommunityGallery } from '../components/CommunityGallery';
import { activities } from '../data';

export function LivedExperiencePage(){return <>
 <section className="relative min-h-[70vh] overflow-hidden bg-[#08155f] pt-20 text-white"><img src="/caminata5kimagen.png" className="absolute inset-0 h-full w-full object-cover opacity-50" alt="Latido y Huella"/><div className="absolute inset-0 bg-gradient-to-t from-[#08155f] via-[#08155f]/65 to-[#08155f]/30"/><div className="relative mx-auto flex min-h-[calc(70vh-80px)] max-w-7xl items-end px-6 py-16"><div className="max-w-4xl"><p className="text-sm font-bold uppercase tracking-[.25em] text-cyan-300">Latido y Huella 2026</p><h1 className="mt-5 text-5xl font-extrabold sm:text-7xl">Todo lo que vivimos</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/80">Una experiencia de comunidad, bienestar, deporte, mascotas y marcas unidas por una causa que sigue creciendo.</p></div></div></section>
 <section className="px-6 py-24"><SectionHeading eyebrow="La historia" title="Un encuentro que se convirtió en memoria" text="Latido y Huella nació para reunir diferentes mundos alrededor de una misma emoción: el vínculo que tenemos con los animales y nuestra capacidad de transformar ese amor en acciones reales."/><div className="mx-auto mt-14 max-w-5xl overflow-hidden rounded-[2rem] bg-[#f3fbfc] p-8 sm:p-12"><p className="text-xl leading-9 text-slate-700">Durante una jornada llena de vida, familias, mascotas, emprendimientos, patrocinadores, voluntarios y organizaciones compartieron actividades, historias y experiencias que hicieron visible la fuerza de esta comunidad.</p><p className="mt-5 text-xl leading-9 text-slate-700">Lo vivido no termina con el cierre del evento. Es el punto de partida para mantener activa una red de personas y marcas que quieren seguir dejando huella.</p></div></section>
 <section className="bg-[#08155f] px-6 py-24"><SectionHeading light eyebrow="La experiencia en imágenes" title="Galería del evento" text="Una selección de momentos oficiales y fotografías compartidas por nuestra comunidad."/><div className="mx-auto mt-14 max-w-7xl"><CommunityGallery limit={12}/></div><div className="mt-10 text-center"><Link to="/movimiento/galeria" className="inline-flex items-center gap-2 rounded-full bg-cyan-400 px-7 py-4 font-bold text-[#08155f]">Ver galería completa <ArrowRight size={18}/></Link></div></section>
 <section className="px-6 py-24"><SectionHeading eyebrow="Voces de la comunidad" title="Testimonios que también dejaron huella"/><div className="mx-auto mt-14 grid max-w-6xl gap-6 md:grid-cols-3">{[
  ['Fue un día para compartir en familia y sentir que todos podíamos aportar a una causa hermosa.','Una familia asistente'],
  ['Ver tantas mascotas, marcas y personas conectadas en un mismo lugar fue realmente especial.','Marca participante'],
  ['Nos llevamos recuerdos, fotografías y muchas ganas de seguir siendo parte del movimiento.','Miembro de la comunidad']
 ].map(([q,n])=><article key={q} className="rounded-[2rem] border border-slate-100 bg-white p-7 shadow-xl shadow-slate-200/50"><Quote className="text-cyan-500"/><p className="mt-5 leading-8 text-slate-700">“{q}”</p><p className="mt-6 text-sm font-bold text-[#0D1B6E]">{n}</p></article>)}</div></section>
 <section className="bg-[#f3fbfc] px-6 py-24"><SectionHeading eyebrow="Una jornada diversa" title="Actividades que nos reunieron"/><div className="mx-auto mt-14 grid max-w-7xl gap-6 md:grid-cols-2 lg:grid-cols-4">{activities.map(a=><article key={a.title} className="overflow-hidden rounded-[2rem] bg-white shadow-lg"><img src={a.image} className="h-48 w-full object-cover" alt={a.title}/><div className="p-6"><h3 className="text-xl font-extrabold text-[#0D1B6E]">{a.title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{a.text}</p></div></article>)}</div></section>
 <SponsorRibbon/>
 <section className="px-6 py-24"><SectionHeading eyebrow="Más personas detrás de la experiencia" title="Expositores, equipo y voluntarios" text="Agradecemos a quienes aportaron su tiempo, talento, productos, servicios y energía para que cada espacio cobrara vida."/><div className="mx-auto mt-12 grid max-w-5xl gap-5 md:grid-cols-2"><div className="rounded-[2rem] bg-[#0D1B6E] p-8 text-white"><Users size={35} className="text-cyan-300"/><h3 className="mt-5 text-2xl">Equipo y voluntarios</h3><p className="mt-3 leading-7 text-white/70">Personas comprometidas que acompañaron la operación, la atención y cada detalle de la jornada.</p></div><div className="rounded-[2rem] bg-cyan-500 p-8 text-[#07104a]"><Camera size={35}/><h3 className="mt-5 text-2xl">Tú también haces parte</h3><p className="mt-3 leading-7 text-[#07104a]/75">Comparte tus fotos y comentarios para seguir construyendo la memoria colectiva del evento.</p><Link to="/deja-tu-huella" className="mt-6 inline-flex items-center gap-2 font-extrabold">Subir mis fotos <ArrowRight size={18}/></Link></div></div></section>
 <section className="bg-[#07104a] px-6 py-24 text-center text-white"><PawIcon/><h2 className="mx-auto mt-5 max-w-3xl text-4xl font-extrabold sm:text-5xl">La experiencia terminó. El movimiento apenas comienza.</h2><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-white/70">Sigue conectado, registra tu mascota, comparte tu historia y acompaña las próximas acciones de Latido y Huella.</p><Link to="/movimiento" className="mt-8 inline-flex rounded-full bg-cyan-400 px-7 py-4 font-extrabold text-[#07104a]">Conoce el movimiento</Link></section>
 </>}
function PawIcon(){return <div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-white/10 text-3xl">🐾</div>}
