[[redirects]]
  from = "https://comparte.latidoyhuella.co/*"
  to = "/deja-tu-huella"
  status = 200
  force = true

[[redirects]]
  from = "https://taquilla.latidoyhuella.co/*"
  to = "/taquilla"
  status = 200
  force = true
  [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200