[build]
  base = "codigo web fronter"
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "codigo web fronter/netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
